//! Router-level integration tests for the scan-planning surface
//! (planTableScan / fetchPlanningResult / cancelPlanning /
//! fetchScanTasks).
//!
//! These require a running Postgres and `DATABASE_URL`; without it they
//! skip (with a note on stderr). Every test provisions its own
//! uniquely-named warehouse rooted in its own tempdir (`file://`
//! storage) and registers fixture tables generated by
//! `meridian_bench::fixture` — real Avro manifests written by the
//! wave-one writers, so pruning and delete attachment are asserted
//! against ground truth, not mocks.

// The shared IdP fixture exposes more than this binary uses.
#[allow(dead_code)]
mod idp;

use std::collections::BTreeSet;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use idp::{AUDIENCE, KID1, TestIdp};
use meridian_bench::fixture::{self, SyntheticSpec};
use meridian_common::AppConfig;
use meridian_common::config::{AuthMode, OidcIssuerConfig};
use meridian_server::{AppState, build_router};
use meridian_store::tenancy;
use serde_json::{Value, json};
use sqlx::PgPool;
use tower::ServiceExt;
use ulid::Ulid;

struct TestCtx {
    router: Router,
    pool: PgPool,
    root: tempfile::TempDir,
    warehouse: String,
}

/// Connects, migrates, creates a tempdir-rooted warehouse, and builds a
/// router with `configure` applied to the config (planning knobs).
async fn test_ctx(configure: impl FnOnce(&mut AppConfig)) -> Option<TestCtx> {
    let Ok(url) = std::env::var("DATABASE_URL") else {
        eprintln!("skipping planning API test: DATABASE_URL is not set");
        return None;
    };

    let mut config = AppConfig::default();
    config.database.url = url;
    configure(&mut config);

    let pool = meridian_store::connect(&config.database)
        .await
        .expect("connect to test database");
    meridian_store::MIGRATOR
        .run(&pool)
        .await
        .expect("run migrations");

    let router = build_router(AppState {
        pool: pool.clone(),
        config: Arc::new(config),
    });

    let root = tempfile::tempdir().expect("create tempdir");
    let warehouse = format!("wh-plan-{}", Ulid::new().to_string().to_lowercase());
    let storage_root = format!("file://{}", root.path().join("warehouse").display());
    let (status, body) = send(
        &router,
        "POST",
        "/api/v2/warehouses",
        None,
        Some(&json!({ "name": warehouse, "storage_root": storage_root })),
    )
    .await;
    assert_eq!(status, StatusCode::CREATED, "create warehouse: {body}");

    Some(TestCtx {
        router,
        pool,
        root,
        warehouse,
    })
}

async fn send_with_token(
    router: &Router,
    method: &str,
    uri: &str,
    token: Option<&str>,
    body: Option<&Value>,
) -> (StatusCode, Value) {
    let mut builder = Request::builder().method(method).uri(uri);
    if let Some(token) = token {
        builder = builder.header("authorization", format!("Bearer {token}"));
    }
    let request = match body {
        Some(body) => builder
            .header("content-type", "application/json")
            .body(Body::from(body.to_string())),
        None => builder.body(Body::empty()),
    }
    .expect("build request");

    let response = router
        .clone()
        .oneshot(request)
        .await
        .expect("infallible router call");
    let status = response.status();
    let bytes = response
        .into_body()
        .collect()
        .await
        .expect("read body")
        .to_bytes();
    let value = if bytes.is_empty() {
        Value::Null
    } else {
        serde_json::from_slice(&bytes).expect("response body is JSON")
    };
    (status, value)
}

async fn send(
    router: &Router,
    method: &str,
    uri: &str,
    token: Option<&str>,
    body: Option<&Value>,
) -> (StatusCode, Value) {
    send_with_token(router, method, uri, token, body).await
}

fn assert_error(body: &Value, code: u16, error_type: &str) {
    assert_eq!(body["error"]["code"], code, "envelope: {body}");
    assert_eq!(body["error"]["type"], error_type, "envelope: {body}");
}

/// Writes a generated fixture into the warehouse tempdir and registers
/// it as `{ns}.{table}`. Returns the plan endpoint base URL.
async fn register_fixture(
    ctx: &TestCtx,
    ns: &str,
    table: &str,
    files: &[(String, Vec<u8>)],
    metadata_location: &str,
) -> String {
    fixture::write_local(files).expect("write fixture files");
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("/v1/{}/namespaces", ctx.warehouse),
        None,
        Some(&json!({ "namespace": [ns] })),
    )
    .await;
    assert!(
        status == StatusCode::OK || status == StatusCode::CONFLICT,
        "create namespace: {body}"
    );
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("/v1/{}/namespaces/{ns}/register", ctx.warehouse),
        None,
        Some(&json!({ "name": table, "metadata-location": metadata_location })),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "register fixture table: {body}");
    format!("/v1/{}/namespaces/{ns}/tables/{table}", ctx.warehouse)
}

/// The fixture's table root inside this test's warehouse tempdir.
fn table_location(ctx: &TestCtx, ns: &str, table: &str) -> String {
    format!(
        "file://{}",
        ctx.root
            .path()
            .join("warehouse")
            .join(ns)
            .join(table)
            .display()
    )
}

fn task_paths(tasks: &Value) -> Vec<String> {
    tasks["file-scan-tasks"]
        .as_array()
        .expect("file-scan-tasks array")
        .iter()
        .map(|t| {
            t["data-file"]["file-path"]
                .as_str()
                .expect("file-path")
                .to_owned()
        })
        .collect()
}

/// Resolves each task's delete references to delete-file paths.
fn deletes_by_task(tasks: &Value) -> Vec<(String, BTreeSet<String>)> {
    let delete_paths: Vec<String> = tasks["delete-files"]
        .as_array()
        .map(|deletes| {
            deletes
                .iter()
                .map(|d| d["file-path"].as_str().expect("delete path").to_owned())
                .collect()
        })
        .unwrap_or_default();
    tasks["file-scan-tasks"]
        .as_array()
        .expect("file-scan-tasks array")
        .iter()
        .map(|t| {
            let path = t["data-file"]["file-path"]
                .as_str()
                .expect("path")
                .to_owned();
            let refs: BTreeSet<String> = t["delete-file-references"]
                .as_array()
                .map(|refs| {
                    refs.iter()
                        .map(|i| {
                            let i = usize::try_from(i.as_u64().expect("index")).expect("usize");
                            delete_paths[i].clone()
                        })
                        .collect()
                })
                .unwrap_or_default();
            (path, refs)
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Endpoint advertisement + kill switch
// ---------------------------------------------------------------------------

#[tokio::test]
async fn config_advertises_planning_endpoints_and_disable_flag_406s() {
    let Some(ctx) = test_ctx(|_| {}).await else {
        return;
    };
    let (status, body) = send(&ctx.router, "GET", "/v1/config", None, None).await;
    assert_eq!(status, StatusCode::OK);
    let endpoints: Vec<&str> = body["endpoints"]
        .as_array()
        .expect("endpoints")
        .iter()
        .filter_map(Value::as_str)
        .collect();
    for expected in [
        "POST /v1/{prefix}/namespaces/{namespace}/tables/{table}/plan",
        "GET /v1/{prefix}/namespaces/{namespace}/tables/{table}/plan/{plan-id}",
        "DELETE /v1/{prefix}/namespaces/{namespace}/tables/{table}/plan/{plan-id}",
        "POST /v1/{prefix}/namespaces/{namespace}/tables/{table}/tasks",
    ] {
        assert!(endpoints.contains(&expected), "missing {expected}: {body}");
    }

    // Disabled: not advertised, and the endpoints answer 406.
    let Some(ctx) = test_ctx(|config| config.planning.enabled = false).await else {
        return;
    };
    let (_, body) = send(&ctx.router, "GET", "/v1/config", None, None).await;
    assert!(
        !body["endpoints"]
            .as_array()
            .expect("endpoints")
            .iter()
            .any(|e| e.as_str().is_some_and(|e| e.contains("/plan"))),
        "planning endpoints must not be advertised while disabled: {body}"
    );
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("/v1/{}/namespaces/ns/tables/t/plan", ctx.warehouse),
        None,
        Some(&json!({})),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_ACCEPTABLE);
    assert_error(&body, 406, "UnsupportedOperationException");
}

// ---------------------------------------------------------------------------
// Synchronous planning: ground truth, stats trimming, lifecycle
// ---------------------------------------------------------------------------

#[tokio::test]
#[allow(clippy::too_many_lines)] // one filter scenario after another
async fn sync_plan_completes_inline_and_matches_ground_truth() {
    let Some(ctx) = test_ctx(|_| {}).await else {
        return;
    };
    let spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "small"),
        data_files: 60,
        partitions: 6,
        files_per_manifest: 10,
        rows_per_file: 1_000,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "plan_ns",
        "small",
        &table.files,
        &table.metadata_location,
    )
    .await;

    // Unfiltered plan: completed inline with every file and a plan-id.
    let (status, body) = send(&ctx.router, "POST", &format!("{base}/plan"), None, None).await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    assert_eq!(body["status"], "completed");
    assert!(body["plan-id"].is_string(), "plan-id is required: {body}");
    assert_eq!(task_paths(&body).len(), 60);
    // No filter -> no residual on tasks.
    assert!(body["file-scan-tasks"][0].get("residual-filter").is_none());

    // Partition filter: exactly one region's files, residual folded to
    // true (identity partition satisfies the whole filter).
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({"filter": {"type": "eq", "term": "region", "value": "region_002"}})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let expected = table.expected(|f| f.region == "region_002");
    assert_eq!(
        task_paths(&body),
        expected,
        "partition pruning ground truth"
    );
    assert_eq!(
        body["file-scan-tasks"][0]["residual-filter"],
        json!({"type": "true"}),
        "identity partition filters fold out of the residual"
    );

    // Stats filter (id range): only files whose id range intersects.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({"filter": {"type": "gt-eq", "term": "id", "value": 55_000}})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let expected = table.expected(|f| f.id_max >= 55_000);
    assert_eq!(task_paths(&body), expected, "stats pruning ground truth");
    assert_eq!(
        body["file-scan-tasks"][0]["residual-filter"],
        json!({"type": "gt-eq", "term": "id", "value": 55000}),
        "non-partition predicates stay in the residual"
    );

    // Combined filter, ground truth from the conjunction.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({"filter": {
            "type": "and",
            "left": {"type": "in", "term": "region", "values": ["region_001", "region_003"]},
            "right": {"type": "lt", "term": "id", "value": 25_000},
        }})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let expected = table
        .expected(|f| (f.region == "region_001" || f.region == "region_003") && f.id_min < 25_000);
    assert_eq!(task_paths(&body), expected, "combined filter ground truth");

    // stats-fields trims the returned per-column maps.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({
            "filter": {"type": "eq", "term": "region", "value": "region_000"},
            "stats-fields": ["id"],
        })),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let file = &body["file-scan-tasks"][0]["data-file"];
    assert_eq!(file["lower-bounds"]["keys"], json!([1]), "{file}");
    assert_eq!(file["value-counts"]["keys"], json!([1]), "{file}");
    // Without stats-fields all stats come back.
    let (_, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({"filter": {"type": "eq", "term": "region", "value": "region_000"}})),
    )
    .await;
    let file = &body["file-scan-tasks"][0]["data-file"];
    assert_eq!(
        file["lower-bounds"]["keys"],
        json!([1, 2, 3, 4, 5]),
        "{file}"
    );
}

#[tokio::test]
#[allow(clippy::too_many_lines)] // submit, fetch, cancel, 404s — one narrative
async fn sync_plan_fetch_and_cancel_lifecycle() {
    let Some(ctx) = test_ctx(|_| {}).await else {
        return;
    };
    let spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "lifecycle"),
        data_files: 20,
        partitions: 2,
        files_per_manifest: 10,
        rows_per_file: 100,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "plan_ns",
        "lifecycle",
        &table.files,
        &table.metadata_location,
    )
    .await;

    let filter = json!({"filter": {"type": "eq", "term": "region", "value": "region_000"}});
    let (status, submitted) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&filter),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {submitted}");
    let plan_id = submitted["plan-id"].as_str().expect("plan id").to_owned();

    // fetchPlanningResult reproduces the inline result (recomputed from
    // the stored request, pinned to the same snapshot).
    let (status, fetched) = send(
        &ctx.router,
        "GET",
        &format!("{base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::OK, "fetch: {fetched}");
    assert_eq!(fetched["status"], "completed");
    assert_eq!(
        fetched["file-scan-tasks"], submitted["file-scan-tasks"],
        "fetch must reproduce the inline planning result exactly"
    );

    // Cancel: 204, then the plan reads back cancelled; cancel again is
    // still 204 (idempotent on terminal states).
    let (status, _) = send(
        &ctx.router,
        "DELETE",
        &format!("{base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::NO_CONTENT);
    let (status, body) = send(
        &ctx.router,
        "GET",
        &format!("{base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, json!({"status": "cancelled"}));
    let (status, _) = send(
        &ctx.router,
        "DELETE",
        &format!("{base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::NO_CONTENT);

    // Unknown plan ids and other tables' plan ids are 404.
    let (status, body) = send(
        &ctx.router,
        "GET",
        &format!("{base}/plan/{}", Ulid::new()),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    assert_error(&body, 404, "NoSuchPlanIdException");

    let other_spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "other"),
        data_files: 5,
        partitions: 1,
        files_per_manifest: 5,
        rows_per_file: 10,
    };
    let other = fixture::synthetic_table(&other_spec).expect("generate fixture");
    let other_base = register_fixture(
        &ctx,
        "plan_ns",
        "other",
        &other.files,
        &other.metadata_location,
    )
    .await;
    let (status, body) = send(
        &ctx.router,
        "GET",
        &format!("{other_base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(
        status,
        StatusCode::NOT_FOUND,
        "a plan id must resolve only under its own table: {body}"
    );
    assert_error(&body, 404, "NoSuchPlanIdException");
}

#[tokio::test]
#[allow(clippy::too_many_lines)] // one rejected request after another
async fn plan_request_validation_errors() {
    let Some(ctx) = test_ctx(|_| {}).await else {
        return;
    };
    let spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "validate"),
        data_files: 5,
        partitions: 1,
        files_per_manifest: 5,
        rows_per_file: 10,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "plan_ns",
        "validate",
        &table.files,
        &table.metadata_location,
    )
    .await;
    let plan_url = format!("{base}/plan");

    // Unknown snapshot.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &plan_url,
        None,
        Some(&json!({"snapshot-id": 42})),
    )
    .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");

    // Point-in-time + incremental together.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &plan_url,
        None,
        Some(&json!({
            "snapshot-id": table.snapshot_id,
            "start-snapshot-id": 1, "end-snapshot-id": 2,
        })),
    )
    .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");

    // start without end.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &plan_url,
        None,
        Some(&json!({"start-snapshot-id": 1})),
    )
    .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");

    // Incremental: honestly not implemented.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &plan_url,
        None,
        Some(&json!({"start-snapshot-id": 1, "end-snapshot-id": 2})),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_ACCEPTABLE, "{body}");
    assert_error(&body, 406, "UnsupportedOperationException");

    // Unknown filter column / select field / stats field.
    for body_json in [
        json!({"filter": {"type": "eq", "term": "ghost", "value": 1}}),
        json!({"select": ["ghost"]}),
        json!({"stats-fields": ["ghost"]}),
    ] {
        let (status, body) = send(&ctx.router, "POST", &plan_url, None, Some(&body_json)).await;
        assert_eq!(status, StatusCode::BAD_REQUEST, "{body_json} -> {body}");
    }

    // Case sensitivity: REGION resolves only case-insensitively.
    let (status, _) = send(
        &ctx.router,
        "POST",
        &plan_url,
        None,
        Some(&json!({
            "filter": {"type": "eq", "term": "REGION", "value": "region_000"},
            "case-sensitive": false,
        })),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let (status, _) = send(
        &ctx.router,
        "POST",
        &plan_url,
        None,
        Some(&json!({"filter": {"type": "eq", "term": "REGION", "value": "region_000"}})),
    )
    .await;
    assert_eq!(status, StatusCode::BAD_REQUEST);

    // Malformed body JSON.
    let request = Request::builder()
        .method("POST")
        .uri(&plan_url)
        .header("content-type", "application/json")
        .body(Body::from("{not json"))
        .expect("build request");
    let response = ctx
        .router
        .clone()
        .oneshot(request)
        .await
        .expect("infallible router call");
    assert_eq!(response.status(), StatusCode::BAD_REQUEST);

    // fetchScanTasks with an unknown token.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/tasks"),
        None,
        Some(&json!({"plan-task": "no-such-token"})),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    assert_error(&body, 404, "NoSuchPlanTaskException");
}

// ---------------------------------------------------------------------------
// Merge-on-read: delete attachment ground truth
// ---------------------------------------------------------------------------

#[tokio::test]
#[allow(clippy::too_many_lines)] // one delete-attachment scenario per block
async fn mor_fixture_attaches_deletes_per_spec_rules() {
    let Some(ctx) = test_ctx(|_| {}).await else {
        return;
    };
    let table =
        fixture::mor_table(&table_location(&ctx, "mor_ns", "orders")).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "mor_ns",
        "orders",
        &table.files,
        &table.metadata_location,
    )
    .await;

    let (status, body) = send(&ctx.router, "POST", &format!("{base}/plan"), None, None).await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    assert_eq!(body["status"], "completed");

    let attachments = deletes_by_task(&body);
    assert_eq!(attachments.len(), 3, "{body}");
    let by_path: std::collections::BTreeMap<&str, &BTreeSet<String>> = attachments
        .iter()
        .map(|(p, refs)| (p.as_str(), refs))
        .collect();
    assert_eq!(
        by_path[table.data_eu_1.as_str()],
        &BTreeSet::from([table.pos_delete.clone(), table.eq_delete.clone()]),
        "seq-1 eu file gets the path-bounded position delete AND the global equality delete"
    );
    assert_eq!(
        by_path[table.data_eu_2.as_str()],
        &BTreeSet::from([table.eq_delete.clone()]),
        "seq-2 eu file misses the position delete's path bounds"
    );
    assert_eq!(
        by_path[table.data_us_1.as_str()],
        &BTreeSet::from([table.eq_delete.clone()]),
        "us file is out of the position delete's partition; the equality delete is global"
    );
    // The delete-files array shapes: position delete + equality delete.
    let delete_contents: BTreeSet<&str> = body["delete-files"]
        .as_array()
        .expect("delete-files")
        .iter()
        .map(|d| d["content"].as_str().expect("content"))
        .collect();
    assert_eq!(
        delete_contents,
        BTreeSet::from(["position-deletes", "equality-deletes"])
    );
    let eq_file = body["delete-files"]
        .as_array()
        .expect("delete-files")
        .iter()
        .find(|d| d["content"] == "equality-deletes")
        .expect("equality delete present");
    assert_eq!(eq_file["equality-ids"], json!([1]), "{eq_file}");
    assert_eq!(eq_file["spec-id"], json!(1), "{eq_file}");

    // A filter that excludes the equality delete's values by stats prunes
    // it: id < 1000 can only match data_eu_1 (ids 0..99), and the
    // equality delete (id = 150150) cannot affect matching rows.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({"filter": {"type": "lt", "term": "id", "value": 1000}})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let attachments = deletes_by_task(&body);
    assert_eq!(attachments.len(), 1, "{body}");
    assert_eq!(attachments[0].0, table.data_eu_1);
    assert_eq!(
        attachments[0].1,
        BTreeSet::from([table.pos_delete.clone()]),
        "the equality delete must be pruned by its equality-column stats"
    );

    // Time travel to the old snapshot: no deletes existed yet.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({"snapshot-id": table.old_snapshot_id})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let paths: BTreeSet<String> = task_paths(&body).into_iter().collect();
    assert_eq!(
        paths,
        BTreeSet::from([table.data_eu_1.clone(), table.data_us_1.clone()])
    );
    assert!(body.get("delete-files").is_none(), "{body}");

    // use-snapshot-schema: the old snapshot's schema has no `category`.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({
            "snapshot-id": table.old_snapshot_id,
            "use-snapshot-schema": true,
            "filter": {"type": "eq", "term": "category", "value": "cat_00"},
        })),
    )
    .await;
    assert_eq!(
        status,
        StatusCode::BAD_REQUEST,
        "filter on a column missing from the snapshot schema: {body}"
    );
    // Same filter against the current schema binds fine.
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/plan"),
        None,
        Some(&json!({
            "snapshot-id": table.old_snapshot_id,
            "filter": {"type": "eq", "term": "category", "value": "cat_00"},
        })),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "{body}");
}

// ---------------------------------------------------------------------------
// Asynchronous planning: lifecycle, pagination, failure
// ---------------------------------------------------------------------------

async fn poll_until(router: &Router, url: &str, want: &str) -> Value {
    for _ in 0..200 {
        let (status, body) = send(router, "GET", url, None, None).await;
        assert_eq!(status, StatusCode::OK, "poll: {body}");
        if body["status"] == want {
            return body;
        }
        assert_eq!(
            body["status"], "submitted",
            "unexpected interim status: {body}"
        );
        tokio::time::sleep(std::time::Duration::from_millis(25)).await;
    }
    panic!("plan did not reach status {want:?} in time");
}

#[tokio::test]
async fn async_plan_lifecycle_pagination_and_cancel() {
    let Some(ctx) = test_ctx(|config| {
        config.planning.sync_max_data_files = 50;
        config.planning.page_size_files = 40;
    })
    .await
    else {
        return;
    };
    let spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "big"),
        data_files: 150,
        partitions: 3,
        files_per_manifest: 50,
        rows_per_file: 100,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "plan_ns",
        "big",
        &table.files,
        &table.metadata_location,
    )
    .await;

    let (status, body) = send(&ctx.router, "POST", &format!("{base}/plan"), None, None).await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    assert_eq!(
        body,
        json!({"status": "submitted", "plan-id": body["plan-id"]}),
        "async submission returns exactly status + plan-id"
    );
    let plan_id = body["plan-id"].as_str().expect("plan id").to_owned();

    let completed = poll_until(&ctx.router, &format!("{base}/plan/{plan_id}"), "completed").await;
    let tokens: Vec<String> = completed["plan-tasks"]
        .as_array()
        .expect("plan-tasks")
        .iter()
        .map(|t| t.as_str().expect("token").to_owned())
        .collect();
    assert_eq!(tokens.len(), 4, "150 files / 40 per page: {completed}");
    assert!(
        completed.get("file-scan-tasks").is_none(),
        "paged results deliver tasks only via fetchScanTasks: {completed}"
    );

    // Fetch every page; the union is exactly the table.
    let mut all_paths: Vec<String> = Vec::new();
    for token in &tokens {
        let (status, page) = send(
            &ctx.router,
            "POST",
            &format!("{base}/tasks"),
            None,
            Some(&json!({"plan-task": token})),
        )
        .await;
        assert_eq!(status, StatusCode::OK, "fetch tasks: {page}");
        let paths = task_paths(&page);
        assert!(paths.len() <= 40, "page size bound: {}", paths.len());
        all_paths.extend(paths);

        // Pages are stable: fetching the same token again returns the
        // identical payload.
        let (_, again) = send(
            &ctx.router,
            "POST",
            &format!("{base}/tasks"),
            None,
            Some(&json!({"plan-task": token})),
        )
        .await;
        assert_eq!(again, page, "fetchScanTasks must be repeatable");
    }
    assert_eq!(all_paths.len(), 150);
    assert_eq!(
        all_paths,
        table.expected(|_| true),
        "pages partition the full file set in order"
    );

    // Cancel the completed plan: tokens die with the pages.
    let (status, _) = send(
        &ctx.router,
        "DELETE",
        &format!("{base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::NO_CONTENT);
    let (status, body) = send(
        &ctx.router,
        "POST",
        &format!("{base}/tasks"),
        None,
        Some(&json!({"plan-task": tokens[0]})),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND, "{body}");
    assert_error(&body, 404, "NoSuchPlanTaskException");
}

#[tokio::test]
async fn async_plan_failure_surfaces_as_failed_status() {
    let Some(ctx) = test_ctx(|config| {
        config.planning.sync_max_data_files = 5;
        // Isolate from other tests' byte caches: the deleted manifest
        // must actually be missed.
        config.planning.pg_cache_max_bytes = 0;
    })
    .await
    else {
        return;
    };
    let spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "broken"),
        data_files: 30,
        partitions: 3,
        files_per_manifest: 10,
        rows_per_file: 100,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "plan_ns",
        "broken",
        &table.files,
        &table.metadata_location,
    )
    .await;

    // Break the table: remove one manifest (but keep the manifest list).
    let manifest_location = table
        .files
        .iter()
        .map(|(loc, _)| loc)
        .find(|loc| loc.contains("/mf-00001"))
        .expect("manifest location");
    std::fs::remove_file(
        manifest_location
            .strip_prefix("file://")
            .expect("file location"),
    )
    .expect("remove manifest");

    let (status, body) = send(&ctx.router, "POST", &format!("{base}/plan"), None, None).await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    assert_eq!(body["status"], "submitted", "{body}");
    let plan_id = body["plan-id"].as_str().expect("plan id").to_owned();

    let failed = poll_until(&ctx.router, &format!("{base}/plan/{plan_id}"), "failed").await;
    assert_eq!(failed["status"], "failed");
    assert!(
        failed["error"]["message"]
            .as_str()
            .is_some_and(|m| m.contains("unreadable")),
        "failure carries the planner error: {failed}"
    );
}

// ---------------------------------------------------------------------------
// Expiry
// ---------------------------------------------------------------------------

#[tokio::test]
async fn expired_plans_answer_404_and_are_swept() {
    let Some(ctx) = test_ctx(|config| config.planning.plan_ttl_secs = 0).await else {
        return;
    };
    let spec = SyntheticSpec {
        table_location: table_location(&ctx, "plan_ns", "ttl"),
        data_files: 5,
        partitions: 1,
        files_per_manifest: 5,
        rows_per_file: 10,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    let base = register_fixture(
        &ctx,
        "plan_ns",
        "ttl",
        &table.files,
        &table.metadata_location,
    )
    .await;

    let (status, body) = send(&ctx.router, "POST", &format!("{base}/plan"), None, None).await;
    assert_eq!(status, StatusCode::OK, "plan: {body}");
    let plan_id = body["plan-id"].as_str().expect("plan id").to_owned();

    // TTL 0: the plan expires immediately — the deadline is enforced on
    // read, not on sweep schedule.
    let (status, body) = send(
        &ctx.router,
        "GET",
        &format!("{base}/plan/{plan_id}"),
        None,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND, "{body}");
    assert_error(&body, 404, "NoSuchPlanIdException");

    // The sweep (what the background task runs) deletes the row.
    let swept = meridian_store::planning::sweep_expired(&ctx.pool, tenancy::default_workspace_id())
        .await
        .expect("sweep");
    assert!(swept >= 1, "at least this test's plan is swept: {swept}");
    let remaining: i64 = sqlx::query_scalar("SELECT count(*) FROM scan_plans WHERE id = $1")
        .bind(&plan_id)
        .fetch_one(&ctx.pool)
        .await
        .expect("count");
    assert_eq!(remaining, 0);
}

// ---------------------------------------------------------------------------
// RBAC: READ on the table, like loadTable
// ---------------------------------------------------------------------------

#[tokio::test]
#[allow(clippy::too_many_lines)] // full oidc setup + the denial/grant matrix
async fn planning_requires_read_on_the_table() {
    let Ok(url) = std::env::var("DATABASE_URL") else {
        eprintln!("skipping planning RBAC test: DATABASE_URL is not set");
        return;
    };
    let idp = TestIdp::start(&[KID1]).await;
    let issuer_url = idp.issuer.clone();

    let mut config = AppConfig::default();
    config.database.url = url;
    config.auth.mode = AuthMode::Oidc;
    config.auth.oidc.require_https_issuers = false;
    config.auth.oidc.issuers.push(OidcIssuerConfig {
        issuer_url,
        audience: AUDIENCE.to_owned(),
        jwks_uri: None,
    });

    let pool = meridian_store::connect(&config.database)
        .await
        .expect("connect to test database");
    meridian_store::MIGRATOR
        .run(&pool)
        .await
        .expect("run migrations");
    let router = build_router(AppState {
        pool: pool.clone(),
        config: Arc::new(config),
    });

    // Bootstrap an admin, then a plain user (JIT-provisioned via config).
    let admin_sub = format!("admin-{}", Ulid::new());
    meridian_store::rbac::bootstrap_admin(
        &pool,
        tenancy::default_workspace_id(),
        &idp.issuer,
        &admin_sub,
    )
    .await
    .expect("bootstrap admin");
    let admin_token = idp::mint(
        KID1,
        &idp.claims(&admin_sub, json!({"email": "admin@example.com"})),
    );
    let user_sub = format!("user-{}", Ulid::new());
    let user_token = idp::mint(
        KID1,
        &idp.claims(&user_sub, json!({"email": "user@example.com"})),
    );
    let (status, _) = send(&router, "GET", "/v1/config", Some(&user_token), None).await;
    assert_eq!(status, StatusCode::OK, "config JIT-provisions the user");
    let user_id: String = sqlx::query_scalar("SELECT id FROM principals WHERE subject = $1")
        .bind(&user_sub)
        .fetch_one(&pool)
        .await
        .expect("provisioned principal");

    // Admin creates the warehouse and registers the fixture.
    let root = tempfile::tempdir().expect("create tempdir");
    let warehouse = format!("wh-planrbac-{}", Ulid::new()).to_lowercase();
    let storage_root = format!("file://{}", root.path().join("warehouse").display());
    let (status, body) = send(
        &router,
        "POST",
        "/api/v2/warehouses",
        Some(&admin_token),
        Some(&json!({"name": warehouse, "storage_root": storage_root})),
    )
    .await;
    assert_eq!(status, StatusCode::CREATED, "create warehouse: {body}");

    let spec = SyntheticSpec {
        table_location: format!(
            "file://{}",
            root.path().join("warehouse/rbac_ns/t").display()
        ),
        data_files: 5,
        partitions: 1,
        files_per_manifest: 5,
        rows_per_file: 10,
    };
    let table = fixture::synthetic_table(&spec).expect("generate fixture");
    fixture::write_local(&table.files).expect("write fixture");
    let (status, body) = send(
        &router,
        "POST",
        &format!("/v1/{warehouse}/namespaces"),
        Some(&admin_token),
        Some(&json!({"namespace": ["rbac_ns"]})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "create namespace: {body}");
    let (status, body) = send(
        &router,
        "POST",
        &format!("/v1/{warehouse}/namespaces/rbac_ns/register"),
        Some(&admin_token),
        Some(&json!({"name": "t", "metadata-location": table.metadata_location})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "register: {body}");

    let base = format!("/v1/{warehouse}/namespaces/rbac_ns/tables/t");

    // Without a grant: every planning endpoint is 403.
    for (method, uri, body) in [
        ("POST", format!("{base}/plan"), Some(json!({}))),
        ("GET", format!("{base}/plan/{}", Ulid::new()), None),
        ("DELETE", format!("{base}/plan/{}", Ulid::new()), None),
        (
            "POST",
            format!("{base}/tasks"),
            Some(json!({"plan-task": "x"})),
        ),
    ] {
        let (status, response) =
            send(&router, method, &uri, Some(&user_token), body.as_ref()).await;
        assert_eq!(
            status,
            StatusCode::FORBIDDEN,
            "{method} {uri} without READ: {response}"
        );
        assert_error(&response, 403, "ForbiddenException");
    }

    // With READ on the table: planning works.
    let (status, body) = send(
        &router,
        "POST",
        "/api/v2/grants",
        Some(&admin_token),
        Some(&json!({
            "privilege": "READ",
            "principal_id": user_id,
            "securable": {
                "type": "table",
                "warehouse": warehouse,
                "namespace": ["rbac_ns"],
                "table": "t",
            },
        })),
    )
    .await;
    assert_eq!(status, StatusCode::CREATED, "grant READ: {body}");
    let (status, body) = send(
        &router,
        "POST",
        &format!("{base}/plan"),
        Some(&user_token),
        Some(&json!({})),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "plan with READ: {body}");
    assert_eq!(body["status"], "completed");
    let plan_id = body["plan-id"].as_str().expect("plan id");
    let (status, body) = send(
        &router,
        "GET",
        &format!("{base}/plan/{plan_id}"),
        Some(&user_token),
        None,
    )
    .await;
    assert_eq!(status, StatusCode::OK, "fetch with READ: {body}");
}
